### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addLeftTile' of undefined

### ISSUE THREAD

**Issue by tiagocasanovapt** [richrace/highlight-selected#109]
[Enter steps to reproduce below:]

1. Disable / Enable "Show in Status bar option"

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.11.1

### Stack Trace

Uncaught TypeError: Cannot read property 'addLeftTile' of undefined

```
At /Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:188

TypeError: Cannot read property 'addLeftTile' of undefined
    at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.setupStatusBar (/Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:188:32)
    at MinimapHighlightSelectedView.setupStatusBar (/Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:200:10
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:624:20
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:809:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:601:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at setNewValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:138:28)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:144:22)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -9:31.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:31.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -9:28.3.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -9:26.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:26.6.0 timecop:view (atom-text-editor.editor.mini)
     -5:14.4.0 atom-trello:toggle (div.package-detail.panels-item)
     -5:10.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:10.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -5:08.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:49.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:49.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:41.3.0 core:backspace (div.package-detail.panels-item)
     -4:34.1.0 color-picker:open (atom-text-editor.editor.mini.is-focused)
     -2:57.2.0 fuzzy-finder:toggle-file-finder (div.package-detail.panels-item)
     -2:54.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "highlight-selected": {
    "hideHighlightOnSelectedWord": true
  }
}
```

### Installed Packages

```coffee
# User
atom-spotify2, v2.1.2
atom-trello, v0.5.1
color-picker, v2.0.14
file-icons, v1.6.13
highlight-selected, v0.11.1
minimap, v4.18.4
minimap-highlight-selected, v4.3.1
monokai, v0.18.0
pigments, v0.19.3
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by richrace** [comment]
Do you still get this error?

**Comment by tiagocasanovapt** [comment]
Indeed, I do. Here is the updated error report.


[Enter steps to reproduce below:]

1. Disable / Enable "Show in Status bar option"

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.11.2


### Stack Trace

Uncaught TypeError: Cannot read property 'addLeftTile' of undefined

```
At /Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:192

TypeError: Cannot read property 'addLeftTile' of undefined
    at MinimapHighlightSelectedView.module.exports.HighlightedAreaView.setupStatusBar (/Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:192:32)
    at MinimapHighlightSelectedView.setupStatusBar (/Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /Users/casanova/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:204:10
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:623:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:808:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:600:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at SettingsPanel.module.exports.SettingsPanel.set (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:196:28)
    at setNewValue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:138:28)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-panel.js:144:22)
    at HTMLInputElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "highlight-selected": {
    "hideHighlightOnSelectedWord": true
  }
}
```

### Installed Packages

```coffee
# User
atom-spotify2, v2.1.2
atom-trello, v0.5.1
color-picker, v2.1.1
editor-stats, v0.17.0
file-icons, v1.6.14
git-log, v0.4.1
highlight-selected, v0.11.2
language-babel, v2.15.2
linter, v1.11.3
linter-swagger, v0.3.4
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
monokai, v0.18.0
pigments, v0.23.0
set-syntax, v0.3.0
sync-settings, v0.6.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by hex2010** [comment]
Is this bug got fixed?  I still got same error when click `Show In Status Bar` checkbox

**Comment by davidbarredo** [comment]
I still got the error
