### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node' after enable

### ISSUE THREAD

**Issue by westtrade** [richrace/highlight-selected#130]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Ubuntu 14.04
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1

### Stack Trace

Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

```
At /opt/atom/resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:72

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at status-bar.StatusBarView.addLeftTile (/opt/atom/resources/app.asar/node_modules/status-bar/lib/status-bar-view.js:72:22)
    at HighlightedAreaView.module.exports.HighlightedAreaView.setupStatusBar (/home/dio/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:192:33)
    at HighlightedAreaView.setupStatusBar (/home/dio/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at HighlightedAreaView.module.exports.HighlightedAreaView.setStatusBar (/home/dio/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:43:6)
    at HighlightedAreaView.setStatusBar (/home/dio/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at Object.module.exports.consumeStatusBar (/home/dio/.atom/packages/highlight-selected/lib/highlight-selected.coffee:51:15)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -7:02.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -7:02.0 core:save (atom-text-editor.editor.is-focused)
     -6:22.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -6:22.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:40.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:40.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:23.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  2x -5:23.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:09.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:09.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:50.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:50.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:49.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -4:49.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -4:34.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
  5x -4:34.4.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "ex-mode",
      "vim-mode",
      "keyboard-sounds",
      "linter-phpmd",
      "tree-view-git-modified",
      "tree-view-breadcrumb",
      "python-jedi",
      "SFTP-deployment",
      "aligner-php",
      "aligner-python",
      "aligner",
      "atom-bootstrap3",
      "atom-drupal-api",
      "atom-live-server",
      "drupal",
      "zip-folder",
      "tree-view-git-branch",
      "tree-view-filter",
      "spec-tree-view",
      "markdown-preview-plus",
      "livereload",
      "linter-rust",
      "linter",
      "less-autocompile",
      "hyperclick",
      "indent-detective",
      "indent-guide-improved",
      "js-hyperclick",
      "js-refactor",
      "keyboard-localization",
      "terminal-plus",
      "go-signature-statusbar",
      "go-config",
      "go-get",
      "go-quick-import",
      "godef",
      "gometalinter-linter",
      "gpp-compiler",
      "language-ejs",
      "merge-conflicts",
      "navigator-godef",
      "npm-install",
      "php-introspector",
      "platformio-ide-terminal",
      "python-snippets",
      "qolor",
      "tree-view-git-status",
      "tree-view-copy-relative-path",
      "tester-go",
      "semicol",
      "selection-highlight",
      "readme"
    ],
    "packagesWithKeymapsDisabled": [
      "zip-folder",
      "git-control"
    ],
    "themes": [
      "atom-dark-ui",
      "gruvbox-plus-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
aligner, v0.22.1 (inactive)
aligner-php, v1.0.0 (inactive)
aligner-python, v1.0.1 (inactive)
atom-beautify, v0.29.10 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-drupal-api, v1.0.1 (inactive)
atom-jade, v0.3.0 (active)
atom-live-server, v1.2.5 (inactive)
atom-trello, v0.5.1 (active)
atom-typescript, v10.1.6 (active)
autocomplete-emojis, v2.5.0 (active)
autocomplete-go, v1.1.0 (active)
autocomplete-paths, v1.0.2 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-python, v1.8.6 (active)
autoupdate-packages, v1.3.1 (active)
block-comment, v0.4.3 (inactive)
build-cargo, v0.16.0 (active)
builder-go, v1.0.0 (active)
comment-headers, v2.15.0 (inactive)
docs-snippets, v0.8.0 (active)
drupal, v1.8.0 (inactive)
emmet, v2.4.3 (active)
emmet-snippets-compatibility, v1.0.6 (active)
environment, v1.2.0 (active)
es6-javascript, v1.0.0 (inactive)
ex-mode, v0.11.0 (inactive)
genesis-ui, v0.5.0 (inactive)
git-authors, v0.1.0 (inactive)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (active)
git-time-machine, v1.5.3 (inactive)
git-travel, v0.1.4 (inactive)
go-config, v1.2.1 (inactive)
go-debug, v0.1.18 (active)
go-get, v1.0.3 (inactive)
go-plus, v4.1.0 (active)
go-quick-import, v0.2.1-rc.0 (inactive)
go-signature-statusbar, v1.1.0 (inactive)
godef, v0.2.5 (inactive)
godoc, v0.3.0 (active)
gofmt, v1.1.6 (active)
gometalinter-linter, v1.1.0 (inactive)
gorename, v1.0.2 (active)
gpp-compiler, v3.0.4 (inactive)
gruvbox-plus-syntax, v1.2.5 (active)
highlight-selected, v0.11.2 (inactive)
hyperclick, v0.0.37 (inactive)
indent-detective, v0.1.0 (inactive)
indent-guide-improved, v1.4.9 (inactive)
jade, v0.1.2 (inactive)
jade-autocompile, v0.8.3 (active)
jade-beautify, v0.1.5 (inactive)
js-hyperclick, v1.4.2 (inactive)
js-refactor, v0.7.3 (inactive)
keyboard-localization, v1.4.18 (inactive)
keyboard-sounds, v0.2.0 (inactive)
language-ejs, v0.2.0 (inactive)
language-qml, v1.0.0 (active)
language-riot-tag, v0.2.2 (active)
language-rust, v0.4.6 (active)
leak-detector, v0.2.1 (inactive)
less-autocompile, v1.0.0 (inactive)
linter, v1.11.16 (inactive)
linter-phpmd, v1.5.0 (inactive)
linter-rust, v0.4.6 (inactive)
livereload, v0.4.4 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.24.7 (active)
navigator-godef, v1.0.3 (inactive)
npm-install, v4.0.3 (inactive)
php-introspector, v1.0.0 (inactive)
platformio-ide-terminal, v2.1.1 (inactive)
project-view, v0.5.0 (active)
project-viewer, v0.3.19 (active)
promote-folder-to-project, v2.0.1 (inactive)
python-debugger, v0.1.0 (inactive)
python-indent, v0.4.3 (active)
python-jedi, v0.3.7 (inactive)
python-snippets, v1.9.0 (inactive)
qolor, v0.2.2 (inactive)
quick-editor, v0.4.3 (inactive)
quick-query, v0.8.4 (inactive)
racer, v0.20.0 (active)
react, v0.16.0 (active)
react-redux-snippets, v0.1.0 (active)
react-snippets, v0.4.2 (active)
readme, v1.0.0 (inactive)
refactor, v0.9.2 (active)
riot, v0.4.1 (active)
rust-api-docs-helper, v0.5.1 (active)
selection-highlight, v0.1.5 (inactive)
semicol, v1.1.1 (inactive)
seti-ui, v1.3.2 (inactive)
SFTP-deployment, v1.0.2 (inactive)
spec-tree-view, v0.1.0 (inactive)
sublime-block-comment, v0.4.0 (inactive)
terminal-plus, v0.14.5 (inactive)
tester-go, v1.0.4 (inactive)
tree-view-breadcrumb, v0.8.1 (inactive)
tree-view-copy-relative-path, v1.0.1 (inactive)
tree-view-filter, v0.4.1 (inactive)
tree-view-git-branch, v0.1.2 (inactive)
tree-view-git-modified, v0.7.1 (inactive)
tree-view-git-status, v1.1.0 (inactive)
vim-mode, v0.65.1 (inactive)
zip-folder, v3.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by richrace** [comment]
Does this still happen with the latest version of Atom (1.15.0)?

**Comment by soyaine** [comment]
still happen
Atom: 1.18.0 x64
highlight-selected 0.13.1

**Comment by richrace** [comment]
What steps do you have to recreate this?
