### ISSUE TITLE
Uncaught TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by beingmrkenny** [richrace/highlight-selected#140]
What I did to trigger this was move the cursor with the arrow keys. It's happening all the time, I've had to disable the plugin.

- Atom 1.13.0 x64
- running on macOS 10.11.16
- Can't find any reference to React Editor

Other plugins:

- Sublime-Style-Column-Selection@1.7.2
- atom-alignment@0.12.1
- atom-beautify@0.29.16
- atom-wrap-in-tag@0.6.0
- auto-update-packages@1.0.1
- block-comment-plus@0.4.0
- change-case@0.6.3
- color-picker@2.2.4
- css-comb@2.5.0
- daylight-ui@0.2.2
- file-icons@2.0.8
- file-types@0.5.4-p1
- highlight-selected@0.12.0
- language-smarty@1.7.0
- linter@1.11.21
- linter-jsonlint@1.3.0
- linter-php@1.3.1
- minimap@4.26.5
- minimap-highlight-selected@4.4.0
- nova-atom-syntax@1.3.1
- nova-atom-ui@1.2.5
- pigments@0.38.0
- remove-whitespace@0.2.1
- seti-ui@1.4.0
- sort-lines@0.14.0
- tabs-to-spaces@1.0.3
- tag@0.4.0
- vim-mode@0.65.2
- yeti-syntax@0.1.2
- yeti-ui@0.1.6

Error on:

`[...]/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:114`

Stack trace:

```
TypeError: Cannot read property 'push' of undefined
    at [...]/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:78:17
    at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:9)
    at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2648:26)
    at FakeEditor.(anonymous function) [as scanInBufferRange] ([...]/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:18:30)
    at MinimapHighlightSelectedView.handleSelection ([...]/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:68:14)
    at MinimapHighlightSelectedView.handleSelection ([...]/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at [...]/minimap-highlight-selected/lib/minimap-highlight-selected-view.coffee:94:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2626:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:924:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:248:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:106:19)
    at DisplayMarker.module.exports.DisplayMarker.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:134:32)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:107:24
    at Selection.module.exports.Selection.modifySelection (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:972:7)
    at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:100:19)
    at Selection.module.exports.Selection.selectWord (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:401:12)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:728:42)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

**Comment by richrace** [comment]
Update `minimap-highlight-selected`.
