### ISSUE TITLE
Failed to activate the highlight-selected package

### ISSUE THREAD

**Issue by SirWaddles** [richrace/highlight-selected#142]
Whenever I launch Atom, I get the error below.

It looks strangely similar to this [completely unrelated error](https://github.com/atom/autocomplete-plus/issues/799)

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Pro
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.12.0

### Stack Trace

Failed to activate the highlight-selected package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module._compile (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\native-compile-cache.js:79:40)
    at Object.value [as .coffee] (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:766:27)
    at Package.module.exports.Package.activateNow (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:181:16)
    at C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:94:15)
    at C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\<user>\AppData\Local\atom\app-1.13.0\resources\app.asar\src\atom-environment.js:831:28
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (inactive)
highlight-selected, v0.12.0 (inactive)
php-twig, v4.0.0 (inactive)
react, v0.16.2 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

After re-installing the package in the Atom interface, I get this error:

```
npm ERR! not a package C:\Users\<user>\AppData\Local\Temp\d-117019-1236-kb4khu\package.tgz
npm ERR! addLocal Could not install C:\Users\<user>\AppData\Local\Temp\d-117019-1236-kb4khu\package.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\<user>\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\<user>\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<user>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<user>\\.atom\\.apmrc" "install" "C:\\Users\\<user>\\AppData\\Local\\Temp\\d-117019-1236-kb4khu\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! path C:\Users\<user>\AppData\Local\Temp\npm-9788-6ac6ab58\unpack-b219b5dc\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\<user>\AppData\Local\Temp\npm-9788-6ac6ab58\unpack-b219b5dc\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\<user>\AppData\Local\Temp\npm-9788-6ac6ab58\unpack-b219b5dc\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
```

This has only been happening since the Atom 1.13 update.

I thought it might have been related to Atom, but I seem to be able to install other packages without issue.

**Comment by SirWaddles** [comment]
I had to delete the %USERPROFILE%/.atom folder to fix this.

Re-installing Atom, clearing the cache, removing all packages, emptying the config, and every other thing I tried didn't work.

I think it's an issue with Electron, and I have no idea why it was only happening for this package.

**Comment by surdu** [comment]
I have the same issue when I open this package in dev mode
