### ISSUE TITLE
Uncaught Error: regular expression is too large

### ISSUE THREAD

**Issue by ebs007** [richrace/highlight-selected#171]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.13.1

### Stack Trace

Uncaught Error: regular expression is too large

```
At C:\Users\MP - Erick\AppData\Local\atom\app-1.26.1\resources\app.asar\node_modules\superstring\index.js:246

Error: regular expression is too large
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:246:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:32)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.26.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1080:32)
    at TextEditor.scanInBufferRange (~/AppData/Local/atom/app-1.26.1/resources/app/src/text-editor.js:3378:73)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:151:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:136:10
    at Array.forEach (native)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:135:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:62:8
```

### Commands

```
     -7:24.2.0 open-html-in-browser:selected-entry (span.name.icon.html5-icon.medium-orange)
     -5:25.1.0 tree-view:copy (span.name.icon.database-icon.medium-yellow)
     -5:22 tree-view:paste (div.header.list-item)
     -4:53.6.0 tree-view:move (span.name.icon.database-icon.medium-yellow)
  7x -4:50.3.0 core:move-right (input.hidden-input)
     -4:47.9.0 core:backspace (input.hidden-input)
  3x -4:47.3.0 core:move-right (input.hidden-input)
     -4:45.4.0 core:delete (input.hidden-input)
  2x -4:44.7.0 core:move-right (input.hidden-input)
  2x -4:42 core:delete (input.hidden-input)
     -4:40.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-bootstrap3 1.2.12 
atom-handlebars 1.3.0 
atom-wrap-in-tag 0.6.0 
auto-detect-indentation 1.3.0 
auto-indent 0.5.0 
autoclose-html 0.23.0 
block-comment-lines 0.2.4 
busy-signal 1.4.3 
close-tags 0.6.0 
close-unmodified-tabs 1.0.1 
docblockr 0.13.7 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.19 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
jquery-snippets 11.0.0 
language-pug 0.0.22 
line-breaker 0.4.0 
line-count 0.5.0 
line-length-break 0.4.0 
linearize 0.1.1 
linter 2.2.0 
linter-csslint 2.0.1 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-less 2.6.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
new-tab 0.5.3 
open-html-in-browser 0.2.1 
open-recent 5.0.0 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
php-integrator-linter-legacy-php56 1.3.1 
pigments 0.40.2 
r0ten-comments 1.1.0 
replace-line-break 1.0.0 
split-diff 1.5.2 
sync-settings 0.8.6 
tab-numbers 0.6.1 
unsaved-changes 0.1.0 
wordpress-api 1.2.2 
zentabs 0.8.9 
```

**Comment by AlexWayfer** [comment]
[Enter steps to reproduce:]

1. Open [`stats.json` file from `yarn` repo](https://github.com/yarnpkg/yarn/blob/2f4bba1/stats.json)

**Atom**: 1.30.0 x64
**Electron**: 2.0.8
**OS**: linux 4.18.5-arch1-1-ARCH
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0


### Stack Trace

Uncaught Error: regular expression is too large

```
At /usr/lib/atom/node_modules/superstring/index.js:252

Error: regular expression is too large
    at TextBuffer.findAllInRangeSync (/usr/lib/atom/node_modules/superstring/index.js:252:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1172:26)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1085:26)
    at TextBuffer.module.exports.TextBuffer.scan (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1057:19)
    at TextEditor.scan (/usr/lib/atom/src/text-editor.js:3525:24)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:172:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:159:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:158:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
     -1:48 intentions:highlight (input.hidden-input)
     -1:47.7.0 core:close (input.hidden-input)
     -1:45 core:move-right (input.hidden-input)
     -1:44.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -1:44.3.0 core:move-left (input.hidden-input)
     -1:43.2.0 intentions:highlight (input.hidden-input)
     -1:43.2.0 core:save (input.hidden-input)
     -1:40.9.0 intentions:highlight (input.hidden-input)
     -1:40.9.0 core:save (input.hidden-input)
     -1:39.7.0 intentions:highlight (input.hidden-input)
     -1:39.6.0 core:close (input.hidden-input)
     -1:10.2.0 intentions:highlight (input.hidden-input)
     -1:10 find-and-replace:show (input.hidden-input)
     -1:08.4.0 core:confirm (input.hidden-input)
     -0:38 intentions:highlight (input.hidden-input)
     -0:38 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-smart-tabs 0.1.0 
atom-typescript 12.6.3 
auto-detect-indentation 1.3.0 
auto-update-plus 0.5.8 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
autocomplete-ruby 0.2.8 
autoupdate-packages 1.3.1 
blocky 0.11.0 
busy-signal 1.4.3 
color-picker 2.3.0 
editorconfig 2.2.2 
file-icons 2.1.24 
genesis-ui 0.5.0 
git-time-machine 2.1.0 
go-plus 5.8.6 
goto-definition 1.3.4 
highlight-selected 0.14.0 
ide-crystal 0.3.3 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-crystal-actual 0.37.2 
language-fish-shell 1.1.0 
language-haml 0.31.1 
language-postcss 1.3.1 
language-vue 0.23.1 
linter 2.2.0 
linter-erb 1.1.1 
linter-eslint 8.4.1 
linter-htmlhint 1.5.0 
linter-jshint 3.1.8 
linter-markdown 5.2.2 
linter-reek 2.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-spell 0.15.0 
linter-stylelint 4.3.2 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monocolor-blue-syntax 2.0.0 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
northem-atom-syntax 2.1.0 
northem-dark-atom-syntax 2.1.0 
nucleus-dark-ui 0.12.3 
platformio-ide-terminal 2.8.4 
precss 0.3.0 
remember-file-positions 0.2.3 
revert-buffer 0.6.0 
ruby-block 0.3.6 
ruby-block-converter 4.1.1 
ruby-define-method 0.2.2 
ruby-test 1.0.2 
seeing-is-believing 15.0.0 
seti-icons 1.5.4 
seti-ui 1.11.0 
single-click-open 0.2.2 
space-tab 0.4.2 
space-underscore 0.1.1 
split-diff 1.5.2 
stacked-tabs 0.1.3 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
tab-control 0.6.11 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
teletype 0.13.3 
term3 0.22.1 
toggle-quotes 1.1.1 
tree-view-open-files 0.3.0 
yard 0.5.1 
zentabs 0.8.9 
```
