### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker layer

### ISSUE THREAD

**Issue by wesgt** [richrace/highlight-selected#181]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.6
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker layer

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:211

Error: Cannot decorate a destroyed marker layer
    at DecorationManager.decorateMarkerLayer (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:211:19)
    at TextEditor.decorateMarkerLayer (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2317:41)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:198:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:159:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:158:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
     -1:35.3.0 core:confirm (input.hidden-input)
  5x -1:22 core:copy (input.hidden-input)
     -1:19.8.0 editor:newline (input.hidden-input)
  8x -1:17 core:move-left (input.hidden-input)
     -1:14.8.0 core:paste (input.hidden-input)
     -1:07.9.0 snippets:previous-tab-stop (input.hidden-input)
     -1:07.9.0 editor:outdent-selected-rows (input.hidden-input)
     -1:07.7.0 snippets:previous-tab-stop (input.hidden-input)
     -1:07.7.0 editor:outdent-selected-rows (input.hidden-input)
     -1:07.5.0 snippets:previous-tab-stop (input.hidden-input)
     -1:07.5.0 editor:outdent-selected-rows (input.hidden-input)
     -1:07.3.0 snippets:previous-tab-stop (input.hidden-input)
     -1:07.3.0 editor:outdent-selected-rows (input.hidden-input)
     -1:07.0 snippets:previous-tab-stop (input.hidden-input)
     -1:07.0 editor:outdent-selected-rows (input.hidden-input)
  7x -0:21 core:copy (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.5 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
expose 0.15.0 
file-icons 2.1.22 
git-plus 8.0.0 
go-debug 1.6.2 
go-plus 5.8.3 
go-signature-statusbar 1.2.3 
goto-definition 1.3.4 
highlight-selected 0.14.0 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-gherkin 1.0.4 
linter 2.2.0 
linter-pylint 2.1.1 
linter-raml 1.0.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
project-manager 3.3.6 
prompt-big-file 0.5.0 
python-tools 0.6.9 
raml 0.2.0 
script 3.18.1 
```

**Comment by richrace** [comment]
Please reopen when you can reproduce it or know how it happened.

**Comment by muram** [comment]
Steps to reproduce:

1. Ctrl+F (find) string in buffer
2. Type something then hit Enter to find
3. Error pops up only when a match is found and highlighted 

**Atom**: 1.28.2 ia32
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0


### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker layer

```
At C:\Users\mmohamed\AppData\Local\atom\app-1.28.2\resources\app\src\decoration-manager.js:211

Error: Cannot decorate a destroyed marker layer
    at DecorationManager.decorateMarkerLayer (~/AppData/Local/atom/app-1.28.2/resources/app/src/decoration-manager.js:211:19)
    at TextEditor.decorateMarkerLayer (~/AppData/Local/atom/app-1.28.2/resources/app/src/text-editor.js:2317:41)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:198:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:159:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:158:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
     -9:22.4.0 project-manager:list-projects (input.hidden-input)
     -9:19.6.0 project-manager:alt-confirm (input.hidden-input)
     -1:03.2.0 intentions:highlight (input.hidden-input)
     -1:02.8.0 find-and-replace:show (input.hidden-input)
  3x -1:01.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-clang 0.11.5 
build 0.70.0 
busy-signal 1.4.3 
file-icons 2.1.22 
file-types 0.5.5 
git-plus 8.0.0 
highlight-selected 0.14.0 
intentions 1.1.5 
json-converter 0.2.4 
language-ini 1.20.0 
linter 2.2.0 
linter-jshint 3.1.8 
linter-jsonlint 1.3.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-highlight-selected 4.6.1 
monokai 0.24.0 
pretty-json 2.0.1 
project-manager 3.3.6 
split-diff 1.5.2 
todo-show 2.3.0 
tool-bar 1.1.7 
```

**Comment by muram** [comment]
@wesg please re-open as I'm able to reproduce in Windows10

**Comment by richrace** [comment]
See https://github.com/danielbrodin/atom-project-manager/issues/386

**Comment by sleeparrow** [comment]
i am getting this error and i do not have project-manager installed

**Comment by outbounder** [comment]
I get it too on Ubuntu 16.04 with Gnome and package v0.14.0 

Further details:

* before upgrading atom packages the issue was not present
* it happens every time when I highlight a word from code block within markdown file which I edit atm.

**Comment by pan-sultan** [comment]
I am getting the same or a similar issue on Linux Mint 19, Atom 3.15.1 x64, highlight-selected 0.15.0.
/home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:221
Hide Stack Trace
Error
    at new EarlyTerminationSignal (/home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:373:7)
    at /home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:192:19
    at TextBuffer.scanInRange (/usr/share/atom/resources/app/static/<embedded>:11:494048)
    at TextBuffer.scan (/usr/share/atom/resources/app/static/<embedded>:11:493504)
    at TextEditor.scan (/usr/share/atom/resources/app/static/<embedded>:11:40885)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:189:14)
    at /home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:161:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:160:27)
    at HighlightedAreaView.handleSelection (/home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /home/alek/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:88:8

is the stack trace not enough to fix this issue?

**Comment by oleg-kosarev** [comment]
[Enter steps to reproduce:]

1. Open large xml files (2.9MB)
2. And focus this files to find

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Deepin 15.9.3
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.15.0


### Stack Trace

Uncaught Error

```
At /home/oleg-kosarev-dev/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:221

Error
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:373:7)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:192:19
    at TextBuffer.scanInRange (/usr/share/atom/resources/app/static/<embedded>:11:494020)
    at TextBuffer.scan (/usr/share/atom/resources/app/static/<embedded>:11:493476)
    at TextEditor.scan (/usr/share/atom/resources/app/static/<embedded>:11:40885)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:189:14)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:161:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:160:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
  2x -3:38 intentions:highlight (input.hidden-input)
     -3:37 core:copy (input.hidden-input)
     -3:35.7.0 intentions:highlight (input.hidden-input)
     -3:35.6.0 core:paste (input.hidden-input)
     -3:05.1.0 intentions:highlight (input.hidden-input)
     -3:04.5.0 core:copy (input.hidden-input)
     -3:00.2.0 editor:newline (input.hidden-input)
 15x -2:46.2.0 core:backspace (input.hidden-input)
  2x -2:35.3.0 core:move-left (input.hidden-input)
     -2:34.8.0 intentions:highlight (input.hidden-input)
     -2:34.6.0 core:paste (input.hidden-input)
  2x -2:34.3.0 intentions:highlight (input.hidden-input)
     -2:29 core:save (input.hidden-input)
     -2:25.9.0 core:backspace (input.hidden-input)
     -2:25.7.0 intentions:highlight (input.hidden-input)
     -2:25.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autocomplete-sql 0.5.0 
autocomplete-xml 0.11.0 
busy-signal 2.0.1 
color-picker 2.3.0 
file-icons 2.1.31 
highlight-selected 0.15.0 
html-to-css 0.2.2 
ide-html 0.5.0 
ide-php 0.7.18 
intentions 1.1.5 
javascript-snippets 1.2.1 
linter 2.3.0 
linter-php 1.6.0 
linter-sass-lint 1.9.0 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-ui-default 1.7.1 
multiple-remote-ftp 1.1.0 
pigments 0.40.2 
remote-ftp 2.2.2 
turbo-javascript 1.4.0 
```

**Comment by BenLeggiero** [comment]
[Enter steps to reproduce:]

1. Double-click or drag-to-highlight a word

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.15.0


### Stack Trace

Uncaught Error

```
At /Users/bleggiero/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:221

Error
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:373:7)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:192:19
    at TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:494333)
    at TextBuffer.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:493789)
    at TextEditor.scan (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:40885)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:189:14)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:161:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:160:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
     -1:48.1.0 core:move-to-bottom (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
highlight-selected 0.15.0 
intentions 1.1.5 
language-log 1.10.1 
language-swift 0.5.0 
linter 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by BenLeggiero** [comment]
This crash appears to be averted in version 0.16.0
