### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by mvbvieira** [richrace/highlight-selected#191]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/layer-decoration.js:17

TypeError: Cannot read property 'onDidDestroy' of undefined
    at new LayerDecoration (/Applications/Atom.app/Contents/Resources/app/src/layer-decoration.js:17:68)
    at DecorationManager.decorateMarkerLayer (/Applications/Atom.app/Contents/Resources/app/src/decoration-manager.js:214:30)
    at TextEditor.decorateMarkerLayer (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2322:41)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:198:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:159:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:158:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at HighlightedAreaView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:109:6)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:32:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didChangeActiveItemOnPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:285:26)
    at Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:444:48)
    at Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:583:18)
    at TabBarView.module.exports.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:730:25)
```

### Commands

```
 11x -7:21.3.0 core:backspace (input.hidden-input)
     -1:27 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:26.5.0 core:paste (input.hidden-input)
     -1:26 core:confirm (input.hidden-input)
  3x -0:53 core:copy (input.hidden-input)
     -0:52.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:52.2.0 core:paste (input.hidden-input)
     -0:51.7.0 core:confirm (input.hidden-input)
  3x -0:31 core:copy (input.hidden-input)
     -0:29.4.0 find-and-replace:show (input.hidden-input)
     -0:29.2.0 core:paste (input.hidden-input)
  7x -0:28.8.0 core:confirm (input.hidden-input)
  2x -0:19.9.0 core:copy (input.hidden-input)
     -0:19.4.0 find-and-replace:show (input.hidden-input)
     -0:19.1.0 core:paste (input.hidden-input)
  6x -0:18.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
clojure-plus 0.3.0 
highlight-selected 0.14.0 
intentions 1.1.5 
linter-ui-default 1.7.1 
lisp-paredit 0.6.0 
project-viewer 1.3.1 
proto-repl 1.4.24 
rails-snippets 2.19.0 
```

**Comment by barnlight** [comment]
[Enter steps to reproduce:]

1. Open a file from a project
2. Change to a different project using Project Viewer
3. Switch back to previous project with the open file
4. Double click any text in the open file
5. Disable and re-enable Highlight addon to fix temporarily

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At C:\Users\mthomas\AppData\Local\atom\app-1.32.2\resources\app\static\<embedded>:14

TypeError: Cannot read property 'onDidDestroy' of undefined
    at new LayerDecoration (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:105346)
    at DecorationManager.decorateMarkerLayer (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:516833)
    at TextEditor.decorateMarkerLayer (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:27615)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:198:12)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:161:8)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
     -2:10.5.0 core:copy (input.hidden-input)
     -0:54.6.0 intentions:highlight (input.hidden-input)
     -0:54.5.0 core:save (input.hidden-input)
     -0:37.5.0 docblockr:parse-enter (input.hidden-input)
     -0:37.5.0 editor:newline (input.hidden-input)
     -0:36.8.0 docblockr:parse-tab (input.hidden-input)
     -0:36.8.0 snippets:next-tab-stop (input.hidden-input)
     -0:36.8.0 snippets:expand (input.hidden-input)
     -0:36.8.0 editor:indent (input.hidden-input)
     -0:21.4.0 docblockr:parse-enter (input.hidden-input)
     -0:21.4.0 editor:newline (input.hidden-input)
     -0:18.6.0 core:move-up (input.hidden-input)
     -0:15.9.0 docblockr:parse-tab (input.hidden-input)
     -0:15.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:15.9.0 snippets:expand (input.hidden-input)
     -0:15.9.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
Atom-SFTP-sync 2.0.1 
atom-toolbar 0.1.6 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
color-picker 2.3.0 
copy-path 0.5.1 
cssnano 1.1.0 
custom-title 1.0.1 
data-atom 0.29.1 
diff-pane 0.3.0 
docblockr 0.13.7 
duplicate-removal 0.1.3 
emmet 2.4.3 
file-icons 2.1.26 
ftp-remote-edit 0.12.19 
git-plus 8.1.0 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
intentions 1.1.5 
language-apache 1.8.0 
language-htaccess 0.2.0 
language-smarty 1.8.0 
language-sql-mysql 0.3.1 
lines 0.13.1 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
notifications-plus 0.69.14 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
project-manager 3.3.6 
project-viewer 1.3.1 
remote-ftp 2.2.0 
Remote-SSH 0.10.0 
remote-sync 4.1.8 
remove-whitespace 0.2.1 
sort-lines 0.18.0 
stacked-tabs 0.1.3 
swackets 0.35.0 
tabs-to-spaces 1.0.5 
tree-view-search-bar 1.0.2 
```

**Comment by earthbound19** [comment]
The same steps detailed by @barnlight duplicate the issue for me, on Mac (and I have the Project-Viewer package installed).

**Comment by nukeop** [comment]
I don't use project viewer and just had this bug too. Just highlighting any random string in the opened file triggers it for me.

**Comment by cmur2** [comment]
For now I reverted to the last known good via `apm install highlight-selected@0.13.1`...

**Comment by x5engine** [comment]
disabled! this is annoying and distracting
