### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by mickeygeecom** [richrace/highlight-selected#194]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Home
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At C:\Users\Mickey Gee\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:177

TypeError: Cannot read property '1' of null
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:177:50
    at TextBuffer.scanInRange (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:494006)
    at TextBuffer.scan (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:493462)
    at TextEditor.scan (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:40885)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:172:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:159:10
    at Array.forEach (<anonymous>)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:158:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:88:8
```

### Commands

```
```

### Non-Core Packages

```
atom-discord-custom 3.0.0 
busy-signal 2.0.0 
fancy-bracket-matcher 2.1.0 
highlight-selected 0.14.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-lua 0.9.11 
linter 2.3.0 
linter-luacheck 2.0.1 
linter-luaparse 0.2.0 
linter-ui-default 1.7.1 
nms-color-bracket 0.1.0 
```

**Comment by ashthespy** [comment]
Just ran into this -- not sure what triggered it, was looking to some large log files.

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.17.0


### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At ~\.atom\packages\highlight-selected\lib\search-model.js:230

TypeError: Cannot read property '1' of null
    at /packages/highlight-selected/lib/search-model.js:186:72
    at TextBuffer.scanInRange (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:497608)
    at TextBuffer.scan (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:497064)
    at TextEditor.scan (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:43334)
    at SearchModel.highlightSelectionInEditor (/packages/highlight-selected/lib/search-model.js:176:14)
    at /packages/highlight-selected/lib/search-model.js:129:21
    at Array.forEach (<anonymous>)
    at SearchModel.handleSelection (/packages/highlight-selected/lib/search-model.js:128:26)
    at /packages/highlight-selected/lib/selection-manager.js:96:26)
    at later (/packages/highlight-selected/node_modules/debounce/index.js:27:23)
```
