### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by ndmax** [richrace/highlight-selected#233]
[Enter steps to reproduce:]

1. Open Atom.
2. Double-click word.

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.17.0

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle

```
At /home/{user}/Cloud/Tech/System/Atom/packages/highlight-selected/lib/search-model.js:230

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle
    at JSON.stringify (<anonymous>)
    at ei.getDecorationManagement (/packages/minimap/dist/main-57e80f3d.js:1:93940)
    at ei.decorateMarker (/packages/minimap/dist/main-57e80f3d.js:1:94835)
    at Object.markerCreated (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:71:12)
    at /packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:47:66
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1171250)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1172691)
    at /packages/highlight-selected/lib/search-model.js:215:41
    at TextBuffer.scanInRange (/usr/share/atom/resources/app/static/<embedded>:11:495518)
    at TextBuffer.scan (/usr/share/atom/resources/app/static/<embedded>:11:494974)
    at TextEditor.scan (/usr/share/atom/resources/app/static/<embedded>:11:40885)
    at SearchModel.highlightSelectionInEditor (/packages/highlight-selected/lib/search-model.js:176:14)
    at /packages/highlight-selected/lib/search-model.js:129:21
    at Array.forEach (<anonymous>)
    at SearchModel.handleSelection (/packages/highlight-selected/lib/search-model.js:128:26)
    at /packages/highlight-selected/lib/selection-manager.js:96:26)
    at later (/packages/highlight-selected/node_modules/debounce/index.js:27:23)
```

### Commands

```
     -1:27.5.0 intentions:highlight (input.hidden-input)
     -1:27.4.0 core:copy (input.hidden-input)
     -1:27.2.0 find-and-replace:show (input.hidden-input)
     -1:22.5.0 intentions:highlight (input.hidden-input)
     -1:22.3.0 core:copy (input.hidden-input)
     -1:21.4.0 intentions:highlight (input.hidden-input)
     -1:21.3.0 core:paste (input.hidden-input)
     -1:20.6.0 intentions:highlight (input.hidden-input)
  2x -1:20.4.0 core:cut (input.hidden-input)
     -1:19.8.0 core:save (input.hidden-input)
     -0:55.3.0 intentions:highlight (input.hidden-input)
     -0:55.1.0 core:copy (input.hidden-input)
     -0:54.9.0 find-and-replace:show (input.hidden-input)
     -0:49 tree-view:toggle (input.hidden-input)
     -0:47.4.0 core:backspace (input.hidden-input)
     -0:47 minimap:toggle (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.46 
find-scroll-marker 0.1.3 
highlight-selected 0.17.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-apache 1.8.0 
language-groovy 0.7.0 
language-lua 0.9.11 
language-powershell 5.0.0 
language-vbscript 0.9.0 
lint-scroll-marker 0.3.0 
linter 3.3.0 
linter-csslint 2.0.6 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-jsonlint 1.4.0 
linter-lua 2.0.0 
linter-php 1.6.1 
linter-sass-lint 1.9.0 
linter-shellcheck 1.6.0 
linter-spell 0.15.0 
linter-ui-default 3.2.0 
minimap 4.39.7 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
pigments 0.40.6 
project-manager 3.3.8 
react 0.18.0 
react-snippets 1.2.0 
scroll-marker 0.3.5 
scroll-through-time 0.3.1 
```

**Comment by ndmax** [comment]
After a simple Atom restart the error no longer appears and I'm not able to reproduce; I don't think there's anything here...
