### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON --> starting at object with constructor 'TextEditor' | property 'decorationManager' -> object with constructor 'DecorationManager' --- property 'editor' closes the circle

### ISSUE THREAD

**Issue by diomat** [richrace/highlight-selected#234]
[Enter steps to reproduce:]

1. Open Atom
2. Create new file
3. Type in a word e.g. "something"
4. Double click word
5. Error gets thrown

I also renamed my ATOM_HOME folder (after the steps) to have a clean start in Atom and only installed the highlight-selected package. After that no error was thrown so it is probably a problem with one of my many other packages. Not sure if this fact makes it a valuable "Issue". Feel free to close immediately :o

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: 
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.17.0

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle

```
At C:\Users\user\.atom\packages\highlight-selected\lib\search-model.js:230

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle
    at JSON.stringify (<anonymous>)
    at Zt.getDecorationManagement (/packages/minimap/dist/main-146015fd.js:1:93664)
    at Zt.decorateMarker (/packages/minimap/dist/main-146015fd.js:1:94559)
    at Object.markerCreated (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:71:12)
    at /packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:47:66
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at /packages/highlight-selected/lib/search-model.js:215:41
    at TextBuffer.scanInRange (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:495557)
    at TextBuffer.scan (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:495013)
    at TextEditor.scan (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:40885)
    at SearchModel.highlightSelectionInEditor (/packages/highlight-selected/lib/search-model.js:176:14)
    at /packages/highlight-selected/lib/search-model.js:129:21
    at Array.forEach (<anonymous>)
    at SearchModel.handleSelection (/packages/highlight-selected/lib/search-model.js:128:26)
    at /packages/highlight-selected/lib/selection-manager.js:96:26)
    at later (/packages/highlight-selected/node_modules/debounce/index.js:27:23)
```

### Commands

```
     -1:25.4.0 intentions:highlight (input.hidden-input)
     -1:25.1.0 project-find:show (input.hidden-input)
  2x -1:22.2.0 find-and-replace:focus-next (input.hidden-input)
     -1:14.5.0 core:confirm (input.hidden-input)
     -0:35.7.0 intentions:highlight (input.hidden-input)
     -0:35.4.0 application:new-file (input.hidden-input)
     -0:30.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:30.6.0 editor:newline (input.hidden-input)
     -0:29.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:29.3.0 editor:newline (input.hidden-input)
     -0:28.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:28.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-browser 1.10.0 
atom-ide-outline 1.17.0 
atom-ide-ui 0.13.0 
atom-mermaid 3.6.0 
atom-monokai 0.10.9 
atom-python-run 0.9.7 
atom-search-everywhere 1.1.0 
autocomplete-date 0.4.0 
autocomplete-paths undefined 
autocomplete-python 1.17.0 
bracket-close-jump 0.2.0 
busy-signal 2.0.1 
character-table 0.4.3 
config-import-export 0.3.1 
cursor-history 0.14.0 
date 2.6.0 
document-outline 2.1.2 
file-icons 2.1.46 
find-scroll-marker 0.1.3 
goto-last-edit 0.3.3 
hard-wrap 1.7.1 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.17.0 
ide-python undefined 
imdone-atom 2.4.33 
indent-guide-improved 1.4.13 
intentions 1.1.5 
jumpy 5.0.2 
keybinding-cheatsheet 0.1.1 
kite 0.202.0 
language-batchfile 0.7.5 
language-markdown 0.37.0 
language-mermaid 0.6.0 
language-powershell 5.0.0 
language-restructuredtext 1.1.2 
language-todo-extras 0.1.0 
language-vbscript 0.9.0 
last-cursor-position 1.2.0 
lint-scroll-marker 0.3.0 
linter 3.3.0 
linter-flake8 2.4.0 
linter-shellcheck 1.6.0 
linter-ui-default 3.2.5 
local-history 4.3.1 
markdown-preview-enhanced 0.18.8 
markdown-preview-plus 4.9.0 
markdown-table-editor 1.1.3 
markdown-toc 0.4.2 
markdown-writer 2.11.11 
minimal-syntax-dark 0.12.4 
minimap 4.39.8 
minimap-codeglance 0.4.7 
minimap-cursorline 1.0.2 
minimap-find-and-replace 5.0.8 
minimap-highlight-selected 4.6.5 
minimap-linter 2.2.2 
minimap-selection 4.5.4 
monokai-seti 0.9.0 
monokai-sublime 1.0.0 
move-cursor-improved 0.3.4 
one-o-eight-syntax 0.40.0 
outline-selection 0.3.2 
pandoc-pdf 0.1.2 
pane-browser 1.6.0 
pdf-view 0.72.0 
pdfjs-viewer 1.0.0 
project-plus 1.0.0 
pubster-syntax 3.1.1 
python-autopep8 0.1.3 
python-indent 1.2.6 
quick-highlight 0.13.0 
rainbow-selection 0.3.2 
rainbow-tabs 2.5.1 
scroll-marker 0.3.5 
seti-ui 1.11.0 
sort-lines 0.19.0 
split-diff 1.6.1 
structure-view 0.2.1 
swackets 0.35.0 
sync-settings 5.2.6 
todo-show 2.3.2 
toggle-markdown-task-with-ongoing 0.0.6 
word-swap 0.1.0 
Zen 0.18.0 
```

**Comment by meowsus** [comment]
Seems related https://github.com/richrace/highlight-selected/issues/233

**Comment by meowsus** [comment]
I compared our plugin lists and tried disabling minimap & minimap-highlight-selected, which seemed to have taken care of this error for me. It's likely this is a bug in their plugin.

**Comment by UziTech** [comment]
This is a bug in minimap https://github.com/atom-minimap/minimap/issues/793.

It happens when the minimap element is hidden but minimap is not disabled. like when using zen mode.
