### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON    --> starting at object with constru...

### ISSUE THREAD

**Issue by okappi0630** [richrace/highlight-selected#235]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.17.0

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle

```
At C:\Users\okapp\.atom\packages\highlight-selected\lib\search-model.js:230

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TextEditor'
    |     property 'decorationManager' -> object with constructor 'DecorationManager'
    --- property 'editor' closes the circle
    at JSON.stringify (<anonymous>)
    at Xt.getDecorationManagement (/packages/minimap/dist/main-8aa714e0.js:1:93955)
    at Xt.decorateMarker (/packages/minimap/dist/main-8aa714e0.js:1:94850)
    at Object.markerCreated (/packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:71:12)
    at /packages/minimap-highlight-selected/lib/minimap-highlight-selected.js:47:66
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at /packages/highlight-selected/lib/search-model.js:215:41
    at TextBuffer.scanInRange (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:495557)
    at TextBuffer.scan (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:495013)
    at TextEditor.scan (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:40885)
    at SearchModel.highlightSelectionInEditor (/packages/highlight-selected/lib/search-model.js:176:14)
    at /packages/highlight-selected/lib/search-model.js:129:21
    at Array.forEach (<anonymous>)
    at SearchModel.handleSelection (/packages/highlight-selected/lib/search-model.js:128:26)
    at /packages/highlight-selected/lib/selection-manager.js:96:26)
    at later (/packages/highlight-selected/node_modules/debounce/index.js:27:23)
```

### Commands

```
     -1:29.8.0 core:move-right (input.hidden-input)
  3x -1:29.5.0 core:backspace (input.hidden-input)
     -1:26.4.0 core:save (input.hidden-input)
     -1:11.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:11.9.0 editor:newline (input.hidden-input)
     -1:10 autocomplete-plus:confirm (input.hidden-input)
     -1:10 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active.has-selection)
  4x -1:05.0 core:undo (input.hidden-input)
  4x -1:02.4.0 core:backspace (input.hidden-input)
     -0:22 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:22 editor:newline (input.hidden-input)
     -0:19.2.0 core:move-down (input.hidden-input)
     -0:18.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:18.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.7.0 core:cut (input.hidden-input)
     -0:12.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
auto-encoding 0.7.2 
autocomplete-paths 2.13.0 
color-picker 2.3.0 
dotinstall-pane 0.3.0 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.47 
git-plus 8.7.1 
highlight-column 0.5.4 
highlight-selected 0.17.0 
imdone-atom 2.4.33 
japanese-menu 1.15.0 
japanese-wrap 0.2.7 
language-markdown 0.37.0 
markdown-table-formatter 2.9.2 
markdown-toc 0.4.2 
maximize-panes 0.2.0 
merge-conflicts 1.4.5 
minimap 4.39.10 
minimap-autohide 0.10.1 
minimap-highlight-selected 4.6.5 
minimap-pigments 0.2.2 
opened-files 0.3.6 
pigments 0.40.6 
project-manager 3.3.8 
remote-edit 1.9.0 
selection-highlight 0.1.6 
show-ideographic-space 1.0.2 
smart-tab-name 1.0.5 
split-diff 1.6.1 
tabs-to-spaces 1.0.5 
tag 0.5.0 
web-search 0.3.3 
```

**Comment by JobJob** [comment]
Dup of #234 - a workaround suggested in [this issue comment](https://github.com/richrace/highlight-selected/issues/234#issuecomment-788163929) is to disable the minimap-highlight-selected package, which worked for me.

**Comment by UziTech** [comment]
This is a bug in minimap https://github.com/atom-minimap/minimap/issues/793.

It happens when the minimap element is hidden but minimap is not disabled. like when using zen mode.
