### ISSUE TITLE
Failed to load the highlight-selected package

### ISSUE THREAD

**Issue by fibric** [richrace/highlight-selected#65]
**Atom Version**: 0.194.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.9.2

### Stack Trace

Failed to load the highlight-selected package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\highlight-selected\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:10:12)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\highlight-selected\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:634:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\denny.trebbin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-flow"
    ],
    "themes": [
      "newton-dark-ui",
      "newton-dark-syntax"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.7.0
atom-ternjs, v0.5.23
autocomplete-bibtex, v0.5.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
git-tab-status, v1.7.0
highlight-column, v0.4.0
highlight-line, v0.10.2
highlight-selected, v0.9.2
linter, v0.12.1
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-eslint, v0.5.2
linter-jsonlint, v0.1.2
linter-stylint, v0.5.0
newton-dark-syntax, v1.1.1
newton-dark-ui, v1.0.4
pigments, v0.1.2
preview-plus, v1.1.19
project-manager, v1.15.5
project-palette-finder, v2.4.17
save-session, vundefined
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by richrace** [comment]
Run the command from the palette: `update package dependencies`

**Comment by fibric** [comment]
Hmm ok but I get this message in response: `Failed to update package dependencies.`

I've tried to rebuild module cache but got another error: Unexpected end of input

```
$ apm rebuild-module-cache
Rebuilding atom-beautify module cache done
Rebuilding atom-ctags module cache done
Rebuilding atom-ternjs module cache done
Rebuilding auto-indent module cache done
Rebuilding autocomplete-bibtex module cache done
Rebuilding autocomplete-paths module cache done
Rebuilding autocomplete-plus module cache done
Rebuilding duotone-dark-syntax module cache done
Rebuilding duotone-light-syntax module cache done
Rebuilding editorconfig module cache done
Rebuilding git-tab-status module cache done
Rebuilding highlight-column module cache done
Rebuilding highlight-line module cache done
Rebuilding highlight-selected module cache failed Unexpected end of input
```

Then I've tried to re-install and now it works for now

```
$ apm uninstall highlight-selected && apm install highlight-selected
```

**Comment by richrace** [comment]
Hmm odd. Well I'll mark this closed as this week I should be removing the `space-pen-views` dependences anyway. 

See: https://github.com/richrace/highlight-selected/pull/60

**Comment by fibric** [comment]
OK and thanks :)
