### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by willl** [richrace/highlight-selected#69]
Steps to reproduce:

1. Open Atom
2. Open Settings (CTRL ,)
3. Close Settings

As soon as I attempt to close that Settings window, the error occurs.

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
  at C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:25:28
  at Set.forEach (native)
  at CompositeDisposable.module.exports.CompositeDisposable.dispose (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:26)
  at HighlightedAreaView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (C:\Users\william\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:27:29)
  at C:\Users\william\.atom\packages\highlight-selected\lib\highlighted-area-view.coffee:13:8
  at Emitter.module.exports.Emitter.emit (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:292:19)
  at Pane.module.exports.Pane.activatePreviousItem (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:263:21)
  at Pane.module.exports.Pane.removeItem (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:372:16)
  at Pane.module.exports.Pane.destroyItem (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\src\pane.js:442:16)
  at HTMLDivElement.<anonymous> (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:183:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\william\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -0:50.5.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".suo",
      ".vsmdi",
      ".vscc",
      ".dll"
    ],
    "disabledPackages": [
      "data-atom",
      "emmet",
      "wrap-guide",
      "js-refactor",
      "refactor"
    ],
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "audioBeep": false
  },
  "highlight-selected": {}
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.2.0
autoclose-html, v0.16.0
highlight-selected, v0.9.2
language-aspx, v0.4.0
language-csharp, v0.5.0
language-cshtml, v0.1.1
language-powershell, v2.0.1
language-sln, v0.1.0
language-vbdotnet, v0.1.0
linter, v0.12.2
monokai, v0.14.0
omnisharp-atom, v0.4.28
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by willl** [comment]
Woops, just noticed there was an update to the package that fixes this. So I'm now going to close this issue :)
