### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by refringe** [richrace/highlight-selected#85]
Don't know what I did to produce this. I started up Atom and opened the release notes. That's when the TypeError appeared.

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.9.2

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25

TypeError: Cannot read property 'dispose' of undefined
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:28
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at HighlightedAreaView.module.exports.HighlightedAreaView.subscribeToActiveTextEditor (/Users/tbrownell/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:60:15)
    at /Users/tbrownell/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:33:24
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
```

### Commands

```
     -0:15.4.0 settings-view:view-installed-packages (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/tbrownell/sites",
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.9.2
minimap, v4.8.0
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by refringe** [comment]
Sorry, there was an update available. Once updated the issue is no more. :smile:
