### ISSUE TITLE
I cannot install this package

### ISSUE THREAD

**Issue by jbass86** [richrace/highlight-selected#91]
I get the following error when running atom after installing the highlight selected package.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package, v0.10.1

### Stack Trace

Failed to load the highlight-selected package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\bassj4\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/bassj4/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:7:7)
    at Object.<anonymous> (/C:/Users/bassj4/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:205:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\bassj4\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
highlight-selected, v0.10.1
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by jbass86** [comment]
instead of trying to install manually I was able to install through the atom settings and it now works ok
